// Rack Turnup Manager - benchmark of completed operations.
//
// Copyright 2026 Summon Software Labs.
// Licensed under the Apache License, Version 2.0.
//
// Methodology: every number below counts COMPLETED operations. Durable
// operations include the whole commit sequence - stage, flush, read back and
// verify, atomic replacement, watermark - because the durable cost is the cost
// that matters. Nothing here measures submission or enqueue latency, and no
// before/after claim is made from this program.
//
// Inputs are labelled: a composition generated by this program is SYNTHETIC,
// while the filesystem, the operating-system lock and the timing are REAL.

#include <chrono>
#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <iomanip>
#include <iostream>
#include <string>
#include <utility>
#include <vector>

#include "rack_turnup/service.hpp"
#include "rack_turnup/state.hpp"
#include "rack_turnup/store.hpp"
#include "rack_turnup/version.hpp"

namespace {

namespace rtm = rackturnup;

struct Measurement {
  std::string name;
  std::string input;
  std::size_t operations = 0;
  double seconds = 0.0;
  std::string note;
};

[[nodiscard]] bool check(const rtm::Status& status) {
  if (!status.has_value()) {
    std::cerr << "benchmark failure: " << rtm::describe(status.error()) << "\n";
    return false;
  }
  return true;
}

[[nodiscard]] double seconds_since(const std::chrono::steady_clock::time_point& start) {
  const auto elapsed = std::chrono::steady_clock::now() - start;
  return std::chrono::duration<double>(elapsed).count();
}

[[nodiscard]] rtm::CompositionMember make_member(std::uint32_t index) {
  rtm::CompositionMember member;
  member.device = rtm::DeviceId::parse("dev:" + std::to_string(index)).value();
  member.slot = rtm::make_slot_coordinate(index + 1, 0).value();
  member.firmware_baseline = rtm::FirmwareBaselineId::parse("fw:2026q1").value();
  member.traits = rtm::TraitSet::create({rtm::Trait::parse("power.ac.208v").value()}).value();
  return member;
}

[[nodiscard]] rtm::MutationContext context_at(std::int64_t at) {
  rtm::MutationContext context;
  context.actor = rtm::ActorId::parse("bench").value();
  context.authority_time = rtm::WallClock(at);
  return context;
}

[[nodiscard]] bool register_and_plan(rtm::TurnupService& service, const std::string& rack_name,
                                    std::uint32_t members, std::int64_t at) {
  const rtm::RackId rack = rtm::RackId::parse(rack_name).value();
  rtm::RegisterRackRequest registration;
  registration.context = context_at(at);
  registration.rack = rack;
  registration.site = rtm::SiteId::parse("site:bench").value();
  for (std::uint32_t index = 0; index < members; ++index) {
    registration.members.push_back(make_member(index));
  }
  const rtm::Result<rtm::RackSummary> registered = service.register_rack(registration);
  if (!registered.has_value()) {
    std::cerr << rtm::describe(registered.error()) << "\n";
    return false;
  }
  rtm::CreatePlanRequest planning;
  planning.context = context_at(at);
  planning.rack = rack;
  planning.expected_rack_generation = registered.value().generation;
  planning.stamp.rack = registered.value().generation;
  planning.stamp.composition = registered.value().composition_generation;
  planning.policy.generation = rtm::PolicyGeneration::initial();
  planning.requirements.required_power_milliwatts = 10000;
  planning.requirements.required_cooling_milliwatts = 5000;
  planning.requirements.required_network_ports = 2;
  const rtm::Result<rtm::RackSummary> planned = service.create_plan(planning);
  if (!planned.has_value()) {
    std::cerr << rtm::describe(planned.error()) << "\n";
    return false;
  }
  return true;
}

[[nodiscard]] bool import_ready_evidence(rtm::TurnupService& service, const std::string& rack_name,
                                        std::uint32_t members, std::int64_t at) {
  const rtm::RackId rack = rtm::RackId::parse(rack_name).value();
  const rtm::RackSummary summary = service.summary(rack, rtm::WallClock(at)).value();
  rtm::PlanRevision revision = summary.revision;
  const auto import = [&](rtm::SubsystemKind subsystem, rtm::EvidencePayload payload) {
    rtm::ImportEvidenceRequest request;
    request.context = context_at(at);
    request.rack = rack;
    request.expected_revision = revision;
    request.subsystem = subsystem;
    request.payload = std::move(payload);
    request.observed_at = rtm::WallClock(at);
    request.validity_from_policy = true;
    const rtm::Result<rtm::EvidenceReceipt> receipt = service.import_evidence(request);
    if (!receipt.has_value()) {
      std::cerr << rtm::describe(receipt.error()) << "\n";
      return false;
    }
    revision = receipt.value().revision;
    return true;
  };

  rtm::EvidencePayload identity;
  identity.kind = rtm::EvidencePayloadKind::IdentityComposition;
  identity.identity.registry_composition = summary.composition;
  identity.identity.declared_members = members;
  if (!import(rtm::SubsystemKind::IdentityComposition, identity)) {
    return false;
  }
  rtm::EvidencePayload power;
  power.kind = rtm::EvidencePayloadKind::Power;
  power.power.domain = rtm::PowerDomainReference::parse("pdu:bench").value();
  power.power.available_milliwatts = 50000;
  power.power.applied_milliwatts = 20000;
  power.power.energized_circuits = 4;
  power.power.redundant_feeds_present = true;
  power.power.applied_verified = true;
  if (!import(rtm::SubsystemKind::Power, power)) {
    return false;
  }
  rtm::EvidencePayload cooling;
  cooling.kind = rtm::EvidencePayloadKind::Cooling;
  cooling.cooling.domain = rtm::CoolingDomainReference::parse("cdu:bench").value();
  cooling.cooling.capacity_milliwatts = 40000;
  cooling.cooling.delivered_milliwatts = 20000;
  cooling.cooling.delivery_verified = true;
  if (!import(rtm::SubsystemKind::Cooling, cooling)) {
    return false;
  }
  rtm::EvidencePayload network;
  network.kind = rtm::EvidencePayloadKind::Network;
  network.network.domain = rtm::NetworkDomainReference::parse("fabric:bench").value();
  network.network.attached_ports = 8;
  network.network.reachable_ports = 8;
  network.network.authority_verified = true;
  if (!import(rtm::SubsystemKind::Network, network)) {
    return false;
  }
  std::vector<rtm::InventoryEntry> entries;
  std::vector<rtm::DeviceHealthSample> samples;
  std::vector<rtm::CompatibilityMembership> membership;
  for (std::uint32_t index = 0; index < members; ++index) {
    const std::string device = "dev:" + std::to_string(index);
    rtm::InventoryEntry entry;
    entry.device = rtm::DeviceId::parse(device).value();
    entry.slot = rtm::make_slot_coordinate(index + 1, 0).value();
    entries.push_back(std::move(entry));
    rtm::DeviceHealthSample sample;
    sample.device = rtm::DeviceId::parse(device).value();
    sample.status = rtm::HealthStatus::Passing;
    samples.push_back(std::move(sample));
    rtm::CompatibilityMembership member;
    member.device = rtm::DeviceId::parse(device).value();
    member.firmware_baseline = rtm::FirmwareBaselineId::parse("fw:2026q1").value();
    member.traits = rtm::TraitSet::create({rtm::Trait::parse("power.ac.208v").value()}).value();
    membership.push_back(std::move(member));
  }
  rtm::EvidencePayload inventory;
  inventory.kind = rtm::EvidencePayloadKind::Inventory;
  inventory.inventory = rtm::create_inventory_observation(std::move(entries), 0).value();
  if (!import(rtm::SubsystemKind::Inventory, inventory)) {
    return false;
  }
  rtm::EvidencePayload health;
  health.kind = rtm::EvidencePayloadKind::Health;
  health.health = rtm::create_health_observation(std::move(samples), 0).value();
  if (!import(rtm::SubsystemKind::Health, health)) {
    return false;
  }
  rtm::EvidencePayload compatibility;
  compatibility.kind = rtm::EvidencePayloadKind::Compatibility;
  compatibility.compatibility =
      rtm::create_compatibility_observation(std::move(membership)).value();
  return import(rtm::SubsystemKind::Compatibility, compatibility);
}

}  // namespace

int main() {
  std::vector<Measurement> measurements;
  const std::filesystem::path directory =
      std::filesystem::temp_directory_path() / "rack-turnup-benchmark";
  std::error_code error;
  std::filesystem::remove_all(directory, error);
  std::filesystem::create_directories(directory, error);
  const std::string state_path = (directory / "state.rtm").string();
  constexpr std::int64_t kTime = 1770000000000ll;

  std::cout << "rack turnup manager " << rtm::version_string() << " (" << rtm::build_configuration()
            << ", " << rtm::build_compiler() << ")\n\n";

  // ---------------------------------------------------------------------
  // 1. Durable evidence imports, including the whole commit sequence.
  // ---------------------------------------------------------------------
  {
    rtm::TurnupService service =
        rtm::TurnupService::open(rtm::StoreOptions{.path = state_path}).value();
    if (!register_and_plan(service, "rack:import", 1, kTime)) {
      return 1;
    }
    constexpr std::size_t kOperations = 300;
    const rtm::RackId rack = rtm::RackId::parse("rack:import").value();
    rtm::PlanRevision revision = service.summary(rack, rtm::WallClock(kTime)).value().revision;
    const auto start = std::chrono::steady_clock::now();
    for (std::size_t index = 0; index < kOperations; ++index) {
      rtm::ImportEvidenceRequest request;
      request.context = context_at(kTime);
      request.rack = rack;
      request.expected_revision = revision;
      request.subsystem = rtm::SubsystemKind::Power;
      request.payload.kind = rtm::EvidencePayloadKind::Power;
      request.payload.power.domain = rtm::PowerDomainReference::parse("pdu:bench").value();
      request.payload.power.available_milliwatts = 50000 + index;
      request.payload.power.applied_milliwatts = 20000 + index;
      request.payload.power.energized_circuits = 4;
      request.payload.power.redundant_feeds_present = true;
      request.payload.power.applied_verified = true;
      request.observed_at = rtm::WallClock(kTime);
      request.validity_from_policy = true;
      const rtm::Result<rtm::EvidenceReceipt> receipt = service.import_evidence(request);
      if (!receipt.has_value()) {
        std::cerr << rtm::describe(receipt.error()) << "\n";
        return 1;
      }
      revision = receipt.value().revision;
    }
    measurements.push_back(Measurement{"durable evidence import", "REAL file, 1 rack", kOperations,
                                       seconds_since(start),
                                       "commit, flush, read back, verify, publish, watermark"});
  }

  // ---------------------------------------------------------------------
  // 2. Readiness evaluation of a synthetic 64 member rack.
  // ---------------------------------------------------------------------
  {
    const std::string evaluation_path = (directory / "evaluation.rtm").string();
    rtm::TurnupService service =
        rtm::TurnupService::open(rtm::StoreOptions{.path = evaluation_path}).value();
    if (!register_and_plan(service, "rack:evaluate", 64, kTime) ||
        !import_ready_evidence(service, "rack:evaluate", 64, kTime)) {
      return 1;
    }
    const rtm::RackId rack = rtm::RackId::parse("rack:evaluate").value();
    constexpr std::size_t kOperations = 2000;
    const auto start = std::chrono::steady_clock::now();
    for (std::size_t index = 0; index < kOperations; ++index) {
      const rtm::Result<rtm::Evaluation> evaluation =
          service.evaluate(rack, rtm::WallClock(kTime + 1000));
      if (!evaluation.has_value()) {
        std::cerr << rtm::describe(evaluation.error()) << "\n";
        return 1;
      }
      if (evaluation.value().verdict != rtm::TurnupVerdict::ReadyToAuthorize) {
        std::cerr << "unexpected verdict "
                  << rtm::turnup_verdict_name(evaluation.value().verdict) << "\n";
        return 1;
      }
    }
    measurements.push_back(Measurement{"readiness evaluation", "SYNTHETIC 64 member rack",
                                       kOperations, seconds_since(start),
                                       "pure function: evidence selection, seven subsystem rules, "
                                       "ladder, blockers, digests"});
  }

  // ---------------------------------------------------------------------
  // 3. Complete durable turnup cycles.
  // ---------------------------------------------------------------------
  {
    const std::string cycle_path = (directory / "cycles.rtm").string();
    rtm::TurnupService service =
        rtm::TurnupService::open(rtm::StoreOptions{.path = cycle_path}).value();
    constexpr std::size_t kCycles = 20;
    const auto start = std::chrono::steady_clock::now();
    for (std::size_t cycle = 0; cycle < kCycles; ++cycle) {
      const std::string rack_name = "rack:cycle" + std::to_string(cycle);
      const rtm::RackId rack = rtm::RackId::parse(rack_name).value();
      if (!register_and_plan(service, rack_name, 4, kTime) ||
          !import_ready_evidence(service, rack_name, 4, kTime)) {
        return 1;
      }
      rtm::AuthorizeRequest authorization;
      authorization.context = context_at(kTime + 2000);
      authorization.rack = rack;
      authorization.expected_revision =
          service.summary(rack, rtm::WallClock(kTime)).value().revision;
      authorization.validity_from_policy = true;
      const rtm::Result<rtm::AuthorizationReceipt> issued =
          service.authorize_turnup(authorization);
      if (!issued.has_value()) {
        std::cerr << rtm::describe(issued.error()) << "\n";
        return 1;
      }
      rtm::RecordActivationRequest activation;
      activation.context = context_at(kTime + 3000);
      activation.rack = rack;
      activation.attempt = issued.value().attempt;
      activation.expected_revision = issued.value().revision;
      activation.outcome = rtm::ActivationOutcome::Active;
      activation.observed_at = rtm::WallClock(kTime + 2500);
      activation.validity_from_policy = true;
      activation.active_members = 4;
      const rtm::Result<rtm::ActivationReceipt> observed = service.record_activation(activation);
      if (!observed.has_value()) {
        std::cerr << rtm::describe(observed.error()) << "\n";
        return 1;
      }
      rtm::CommissionRequest commission;
      commission.context = context_at(kTime + 4000);
      commission.rack = rack;
      commission.attempt = issued.value().attempt;
      commission.expected_revision = observed.value().revision;
      const rtm::Result<rtm::CommissionReceipt> commissioned = service.commission(commission);
      if (!commissioned.has_value()) {
        std::cerr << rtm::describe(commissioned.error()) << "\n";
        return 1;
      }
    }
    measurements.push_back(Measurement{"complete turnup cycle", "REAL file, 4 member rack", kCycles,
                                       seconds_since(start),
                                       "register, plan, seven evidence imports, authorize, "
                                       "activate, commission, all durable"});
  }

  // ---------------------------------------------------------------------
  // 4. Durable state codec.
  // ---------------------------------------------------------------------
  {
    const std::string codec_path = (directory / "cycles.rtm").string();
    const rtm::ServiceState state =
        rtm::DurableStore::read_only_load(codec_path).value();
    constexpr std::size_t kOperations = 500;
    const auto start = std::chrono::steady_clock::now();
    for (std::size_t index = 0; index < kOperations; ++index) {
      const std::vector<std::uint8_t> encoded = rtm::encode_state(state).value();
      const rtm::ServiceState decoded = rtm::decode_state(encoded).value();
      if (!rtm::digests_equal(rtm::compute_state_digest(decoded),
                              rtm::compute_state_digest(state))) {
        std::cerr << "codec round trip changed the state\n";
        return 1;
      }
    }
    measurements.push_back(Measurement{"state encode and decode", "REAL 20 rack state", kOperations,
                                       seconds_since(start),
                                       "canonical encode, full validation on decode"});
  }

  std::cout << std::left << std::setw(28) << "completed operation" << std::setw(28) << "input"
            << std::right << std::setw(10) << "ops" << std::setw(12) << "seconds" << std::setw(14)
            << "ops/second" << std::setw(14) << "ms/op" << "\n";
  for (const Measurement& measurement : measurements) {
    const double per_second =
        (measurement.seconds > 0.0) ? (measurement.operations / measurement.seconds) : 0.0;
    const double milliseconds = (measurement.operations > 0)
                                    ? (measurement.seconds * 1000.0 / measurement.operations)
                                    : 0.0;
    std::cout << std::left << std::setw(28) << measurement.name << std::setw(28) << measurement.input
              << std::right << std::setw(10) << measurement.operations << std::setw(12) << std::fixed
              << std::setprecision(3) << measurement.seconds << std::setw(14) << std::setprecision(1)
              << per_second << std::setw(14) << std::setprecision(3) << milliseconds << "\n";
    std::cout << "    " << measurement.note << "\n";
  }
  std::cout << "\nmethodology: completed operations only; durable numbers include flush, read back, "
               "verify, atomic publish and watermark\n";
  std::cout << "inputs: compositions generated by this program are SYNTHETIC; the filesystem, the "
               "operating-system lock and the timing are REAL\n";
  std::filesystem::remove_all(directory, error);
  return 0;
}
